# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 16:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pconsumer', '0002_connection'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('room', 'user')]),
        ),
    ]
